@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.direwolf20.buildinggadgets.common.schema.template;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;