@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.direwolf20.buildinggadgets.common.schema.template.provider;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;