@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.direwolf20.buildinggadgets.common.capability;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
