name: Auto Release

on:
  push:
    tags:
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK  17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Build & Publish to Github Maven
        run: |
          chmod +x ./gradlew
          ./gradlew build publish --no-daemon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        env:
          CURSE_TOKEN: ${{ secrets.CURSE_TOKEN }}
        run: ./gradlew curseforge --no-daemon
      - name: Release to Github
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          body_path: ./CHANGELOG.md
          files: build/libs/*.jar