name: Auto Release

on:
  push:
    tags:
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Publish to Maven & Curseforge
        uses: gradle/gradle-build-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CURSE_TOKEN: ${{ secrets.CURSE_TOKEN }}
        with:
          arguments: build publish curseforge
      - name: Release to Github
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          body_path: ./CHANGELOG.md
          files: build/libs/*.jar
